app/views/components/primary-navigation/index.html, app/views/index.html, app/views/layouts/base.html, src/components/_all.scss, src/components/moj-primary-navigation/README.md, src/components/moj-primary-navigation/_primary-navigation.scss, src/components/moj-primary-navigation/macro.njk, src/components/moj-primary-navigation/template.njk
=> Add primary navigation component

app/views/components/sub-navigation/index.html, app/views/index.html, app/views/layouts/base.html, src/components/_all.scss, src/components/moj-sub-navigation/README.md, src/components/moj-sub-navigation/_sub-navigation.scss, src/components/moj-sub-navigation/macro.njk, src/components/moj-sub-navigation/template.njk
=> Add sub navigation component

app/views/components/currency-input/index.html, app/views/index.html, app/views/layouts/base.html, src/components/_all.scss, src/components/moj-currency-input/README.md, src/components/moj-currency-input/_currency-input.scss, src/components/moj-currency-input/macro.njk, src/components/moj-currency-input/template.njk
=> Add currency input component

app/views/components/progress-bar/index.html, app/views/index.html, app/views/layouts/base.html, src/components/_all.scss, src/components/moj-progress-bar/README.md, src/components/moj-progress-bar/_progress-bar.scss, src/components/moj-progress-bar/macro.njk, src/components/moj-progress-bar/template.njk
=> Add progress bar component

app/views/components/header/index.html, app/views/index.html, app/views/layouts/base.html, src/components/_all.scss, src/components/moj-header/README.md, src/components/moj-header/_header.scss, src/components/moj-header/macro.njk, src/components/moj-header/template.njk
=> Add header component

app/views/components/notification-badge/index.html, app/views/index.html, app/views/layouts/base.html, src/components/_all.scss, src/components/moj-notification-badge/README.md, src/components/moj-notification-badge/_notification-badge.scss, src/components/moj-notification-badge/macro.njk, src/components/moj-notification-badge/template.njk
=> Add notification badge component

app/views/components/header/index.html, src/components/moj-header/README.md, src/components/moj-header/template.njk
- Add documentation (Nunjucks params)
- Change `organisation` to `organisationLabel`
- Change `service` to `serviceLabel`
=> Update header component documentation

src/components/moj-primary-navigation/README.md, src/components/moj-primary-navigation/template.njk
- Add component examples
- Add component argument definitions
=> Update primary navigation documentation

src/components/moj-sub-navigation/README.md, src/components/moj-sub-navigation/template.njk
- Add component examples
- Add component argument definitions
=> Update sub navigation documentation

app/assets/sass/application.scss, app/assets/sass/components/_app-swatch.scss, app/views/components/tag/index.html, app/views/index.html, src/components/_all.scss, src/components/moj-tag/README.md, src/components/moj-tag/_tag.scss
Added:
- Styles
- Documentation
=> Add tag component styles

app/views/components/badge/index.html, src/components/moj-badge/_badge.scss
- Flip small to large
- Fix padding
=> Update badge styles

app/views/components/organisation-switcher/index.html, src/components/moj-organisation-switcher/_organisation-switcher.scss, src/components/moj-organisation-switcher/template.njk
=> Fix organisation switcher spacing and wrapping

app/views/components/filter-layout/index.html, app/views/components/filter/index.html, app/views/includes/scripts.html, app/views/index.html, src/components/_all.scss, src/components/moj-action-bar/README.md, src/components/moj-action-bar/_action-bar.scss, src/components/moj-filter-toggle-button/README.md, src/components/moj-filter-toggle-button/filter-toggle-button.js
This makes the filter be toggleable with the toggle button working responsively as part of a table action bar.
=> Filter toggle and layout

src/components/moj-currency-input/_currency-input.scss, src/components/moj-header/_header.scss, src/components/moj-identity-bar/_identity-bar.scss, src/components/moj-page-header-actions/_page-header-actions.scss, src/components/moj-pagination/_pagination.scss, src/components/moj-primary-navigation/_primary-navigation.scss, src/components/moj-sub-navigation/_sub-navigation.scss, src/objects/_width-container.scss
=> Update mq to govuk-media-query mixin

README.md, app.json, package/README.md, src/components/moj-action-bar/README.md, src/components/moj-add-another/README.md, src/components/moj-badge/README.md, src/components/moj-currency-input/README.md, src/components/moj-filter-toggle-button/README.md, src/components/moj-form-validator/README.md, src/components/moj-header/README.md, src/components/moj-menu/README.md, src/components/moj-notification-badge/README.md, src/components/moj-page-header-actions/README.md, src/components/moj-pagination/README.md, src/components/moj-password-reveal/README.md, src/components/moj-primary-navigation/README.md, src/components/moj-rich-text-editor/README.md, src/components/moj-search/README.md, src/components/moj-sortable-table/README.md, src/components/moj-sub-navigation/README.md, src/components/moj-tag/README.md, src/components/moj-timeline/README.md
=> Update references to design system and frontend

app/views/components/messages/index.html, app/views/components/messages/styles.html, app/views/index.html, app/views/layouts/base.html, package-lock.json, src/components/_all.scss, src/components/moj-messages/README.md, src/components/moj-messages/_messages.scss, src/components/moj-messages/macro.njk, src/components/moj-messages/template.njk
Add a component to display messages between two actors, for example: caseworkers and legal professionals.
Resolves following issue on backlog: 
https://github.com/ministryofjustice/mojdt-design-system-backlog/issues/14
_NB. it's worth creating a pattern to demonstrate the message component in situ with input._
=> Component messages

src/moj/components/button-menu/_button-menu.scss, src/moj/components/button-menu/template.njk
A little tidy-up of the button menu component
=> Update button menu component

app/views/components/task-list/index.html, app/views/index.html, app/views/layouts/base.html, src/moj/components/_all.scss, src/moj/components/task-list/README.md, src/moj/components/task-list/_task-list.scss, src/moj/components/task-list/macro.njk, src/moj/components/task-list/template.njk
Fix #74 – The task list is in the GOV.UK Prototype Kit but not in the GOV.UK Design System, which is strange as they mention the pattern. That said, I have added it to the MOJ Frontend as an interim solution.
=> Add task list component

src/moj/components/add-another/add-another.js
- Are you fixing a bug? Yes https://github.com/ministryofjustice/moj-frontend/issues/82
- Are you improving performance?No
- Are you updating documentation? No
- Are you changing functionality? No
2. Replace this text with the contents of the template
3. Fill in all sections of the template
4. Click "Create pull request".
=> Fix to add another functionality when a hint exists

src/moj/components/pagination/_pagination.scss
Changed Pagination to use CSS instead of SVG, as discussed on Slack
=> Use CSS to create arrows for pagination

.releaserc.json, package.json
Debugging enabled for semantic-release to get more feedback as to the issue of releasing
N/A
N/A
N/A
N/A
N/A
=> Ci1 - Debug enabled

.releaserc.json
Tag format changed to include alpha and enable for master
N/A
N/A
N/A
N/A
N/A
=> ci: tag format changed to include alpha and enable for master

package.json
Potential fix for missing alpha dist tag in npm package
N/A
N/A
N/A
N/A
N/A
=> fix: potential fix for missing alpha dist tag in npm package

.releaserc.json, package.json
Fix for package contents not distributing correct files
Packages will actually contain the correct files
N/A
N/A
N/A
N/A
=> fix: fix for package contents not distributing correct files

CHANGELOG.md, CONTRIBUTING.md, README.md
Updates documentation to be in line with new semvar versioning.
* Changed format of changelog to match semantic release bullet points
* added circle badge
* updated contribution guidelines
=> docs(readme): updated documentation with latest changes

CHANGELOG.md
Removed Changelog title to potentially fix the display in Github
Removed Changelog title
=> docs(changelog): removed title in changelog to better work with github

package-lock.json, package.json
Updates dependencies within package.json to their latest versions.
Latest versions of the design system and security patches for other packages.
None that can be thought of
Ran `npm run build:package` to check no errors resulted from the upgrades. Results outputted correctly
None
- Updates dependencies within package.json to their latest versions.
=> chore(package): updates dependencies in package.json

app/views/components/ticket-panel/index.html, src/moj/components/ticket-panel/_ticket-panel.scss
The bug is a purely visual one with missing colour options, grey in particular.
Adds a grey option and tidies up the examples. 
Also adds some sizing issues for various devices to ensure consistency on smaller devices.
=> fix(ticket-panel): fixes the colour options within the panel

.github/workflows/pull_request.yml, package-lock.json, package.json, test.scss
This action imports the latest version of the app, imports it and builds the SCSS. We can then run
`npm test` to check that it builds correctly.
=> Add PR action to build the app

package-lock.json, package.json
This fixes a few vulnerabilities in our toolchain. We wouldn't necessarily be affected by any of these, but it's best to be safe.
=> chore: update various dependencies

docs/examples/page-header-actions/index.njk
Previous PR didn't quite get it
=> docs: fix bad syntax

.eleventy.js, .github/workflows/docs.yml, docs/components/add-another.md, docs/components/badge.md, docs/components/banner.md, docs/components/button-menu.md, docs/components/currency-input.md, docs/components/filter.md, docs/components/form-validator.md, docs/components/header.md, docs/components/identity-bar.md, docs/components/messages.md, docs/components/multi-file-upload.md, docs/components/multi-select.md, docs/components/notification-badge.md, docs/components/organisation-switcher.md, docs/components/page-header-actions.md, docs/components/pagination.md, docs/components/password-reveal.md, docs/components/primary-navigation.md, docs/components/rich-text-editor.md, docs/components/search.md, docs/components/side-navigation.md, docs/components/sortable-table.md, docs/components/sub-navigation.md, docs/components/tag.md, docs/components/timeline.md
Uses a new "lastUpdated" filter to automatically calculate the point at which the component's
source code was last changed (by analysing Git logs). Also provides a link to that change.
Also forces the docs to rebuilt on *every* push to main, so that changes to components are
immediately reflected in the last updated date.
<details>
<summary>Example</summary>
</details>
=> docs: add last updated date to components

.github/workflows/docs.yml
Checkout the entire repo history so we can check when components were last changed
=> docs: fix "Last updated" dates

docs/components/add-another.md
The previous text suggested that the Add Another component would itself handle non-JavaScript users, which is misleading. The component relies on JavaScript and non-JS users must be handled by the (bespoke) backend
=> docs(add-another): clarify wording RE JavaScript

docs/get-started/installing-compiled.md, docs/get-started/production.md
Now that we release compiled files, explain how to use them.
<details>
<summary>Page preview</summary>
</details>
=> docs: document installation with compiled files

.github/workflows/docs.yml, .github/workflows/main.yml
Use LTS node and latest actions/setup-node
=> build: fix build scripts

docs/patterns/filter-a-list.md
=> typo - "acan" should be "can"

package-lock.json
Bump ejs, async, js-beautify, uglify-js to avoid vulnerabilities
=> build: bump some patch dependencies

package/govuk-prototype-kit.config.json, src/moj/filters/prototype-kit-13-filters.js
In version 13 of GOV.UK Prototype Kit we have some new integration points.  This makes use of the new integration points and makes the installation simpler for users.  Specifically, for `moj-frontend`, this will import all the nunjucks macros (components) and filters without the user having to do any setup themselves.
You could leave the `govuk-prototype-kit.config.json` as-is and it will still work with the same features.  The mechanism for including filters has changed so users of the kit would need to add some code to their prototypes to handle this.
Ultimately, using the config saves the kit user from having to wire these things in for themselves.  The alternative is to instruct users on how to integrate these features.
The only concern I have is for a potential conflict with the …
=> feat(prototype kit integration): users of prototype-kit-v13 should have macros and filters available

package-lock.json
This allows the docs to be built on Node v17+
=> build(deps): bump Webpack to 5.74.0

.github/workflows/deploy-staging.yaml
Fix branch and file references
=> chore: auto-stage PRs by pushing straight to Kubernetes

.github/workflows/tag-staging.yml
Fix branch and file references
#417 targetted the wrong file
=> chore: auto-stage PRs by pushing straight to Kubernetes 

Dockerfile, docker/nginx.conf
Rather than editing the file inline, have an explicit nginx config file
Also add `absolute_redirect off;` so that nginx stops trying to redirect all requests onto port 3000.
=> docs: fix staging nginx config

docs/components/add-another.md, docs/components/filter.md, docs/components/side-navigation.md, docs/components/ticket-panel.md
Credit to @tom-rooker-moj and @euhyung for the content
=> docs: document known accessibility issues on components

docs/_includes/layouts/community.njk, docs/_includes/layouts/partials/navigation.njk, docs/community/index.md, docs/community/roadmap.md, docs/community/updates.md, package-lock.json
**Description of the change**
Addition of community pages to communicate latest updates and the roadmap for the MOJ Design System.
=> docs(community update information): addition of community pages

docs/community/roadmap.md, docs/community/updates.md
- Roadmap updated to show completed tasks.
- Completed tasks added to latest updates.
=> docs(roadmap update): strike through of completed tasks

docs/_includes/layouts/base.njk, docs/_includes/layouts/home.njk, docs/_includes/layouts/partials/header.njk, docs/accessibility.md, docs/cookies.md, docs/get-in-touch.md, docs/get-started/index.md, docs/get-started/installing-compiled.md, docs/get-started/production.md, docs/get-started/prototyping.md, docs/get-started/setting-up-javascript.md
Find-and-replace exercise throughout the public site to change the name from MOJ Pattern Library to MOJ Design System.
=> docs(name change): change of name from Pattern Library to Design System

docs/_includes/layouts/base.njk, docs/_includes/layouts/partials/feedback-banner.njk, docs/community/roadmap.md, docs/community/users-and-data.md
- Feedback banner added to all pages below header and primary navigation
- Feedback banner links to Google Form
- PR includes content updates to roadmap
=> docs(feedback banner): feedback banner added to site

.eleventy.js, docs/_includes/example.njk, docs/examples/badge/index.njk
So we can deep-link to the component in the MoJ Figma Kit
=> docs: add support for figma links

docs/_includes/layouts/component.njk, docs/community/users-and-data.md, docs/components/date-picker.md
A Date Picker component has been proposed into the MoJ Design System. This new page on the public site is to demonstrate progress on developing the contribution into a reusable component that can be reused.
=> docs(new component in development): date picker component in development

docs/examples/identity-bar-menu-toggle/index.njk, docs/examples/identity-bar-menu/index.njk, docs/examples/identity-bar-secondary-toggle/index.njk, docs/examples/multi-file-upload/index.njk, docs/examples/multi-select/index.njk
Version of the Multi Select and Multi File Upload components created in Figma. Link to Figma included on the component pages.
=> docs(adding figma links for multi file upload and multi select components)

.eleventy.js, docs/components/multi-file-upload.md, docs/examples/button-menu-collapsible-alternative/script.js, docs/examples/button-menu-collapsible/script.js, docs/examples/identity-bar-menu-toggle/script.js, docs/examples/identity-bar-secondary-toggle/script.js, docs/examples/multi-file-upload/script.js, docs/examples/patterns/filter-a-list/script.js, docs/examples/primary-navigation-toggle-search/index.njk, src/moj/components/button-menu/button-menu.js, src/moj/components/filter-toggle-button/filter-toggle-button.js, src/moj/components/multi-file-upload/multi-file-upload.js, src/moj/components/primary-navigation/_primary-navigation.scss, src/moj/components/search-toggle/search-toggle.js, src/moj/components/side-navigation/_side-navigation.scss, src/moj/components/sub-navigation/_sub-navigation.scss
A merge of #520, #545 and #557 to fix two accessibility issues and remove the external dependency on jQuery.
=> Release 2.1.0

docs/community/help-and-feedback.md
- Fill out the template below. Maintainers are free to close any pull requests that do not include enough information, at their discretion.
- The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at https://github.com/ministryofjustice/moj-frontend/tree/main/.github/PULL_REQUEST_TEMPLATE.
Change 'Contact us **on** email' to 'Contact us **by** email'.
N/A
=> docs(contact): change 'contact us on email' to 'contact us by email'

.github/workflows/main.yml
=> build(deps): upgrade upload/download-artifact actions

src/moj/components/sortable-table/sortable-table.js
=> Sortable table fix

docs/_includes/layouts/ethics.njk, docs/ethics/index.md, docs/ethics/principles.md
- Text changes to ethics pages
- Changing order of pages within side navigation of ethics pages
=> docs: update to ethics guidance

docs/_includes/arguments/date-picker.md
=> docs (datepicker): update Nunjucks content

docs/ethics/assessment.md, docs/ethics/index.md, docs/ethics/review.md
Updating ethics content resulting from conversations with the ethics rocketship.
=> docs (ethics): update content

.github/ISSUE_TEMPLATE/TASK.md
Previous TASK template wasn't available when adding an issue. Updated file to include .md
=> Update and rename TASK to TASK.md

docs/examples/pagination/index.njk
=> docs(pagination): changing pages to results

kubernetes-deploy-production.tpl
Reverts ministryofjustice/moj-frontend#741
=> Revert "build(deployment): remove default cloudplatform site"

.github/ISSUE_TEMPLATE/TASK.md
- Task template updated to include a definition of done.
- Accessibility Specialist added to list of people to involve.
=> docs(task.md): updating task template to include a definition of done

docs/_includes/layouts/base.njk, gulp/docs.js
add a quick version number to the JS bundle file
=> docs(js): add quickfix version to js file

docs/_includes/layouts/base.njk, gulp/docs.js, package-lock.json
add quick version number to css
=> Add temp asset version

docs/_includes/layouts/base.njk, gulp/docs.js
bumps the asset version number to cachebust
=> docs(assets): bump assets version

.github/ISSUE_TEMPLATE/TASK.md
- Added User Researcher and Performance Analyst to roles in the task template
=> Adding new roles to task template

docs/assets/stylesheets/components/_prose.scss
- Updated background colour of <code> tag
- Reduced font size to look visually similar when mid-sentence
=> style: 💄 updating inline code style

jest.config.js
=> test: fix urls

src/moj/components/date-picker/date-picker.spec.js
=> test(date picker): fix date manipulation in date picker tests

docs/examples/sortable-table/index.njk, docs/examples/ticket-panel/index.njk
Adding Figma links for sortable table and ticket panel.
=> docs: add Figma links

docs/get-involved/suggest-a-change.md
- Tweak to suggest a change page
=> Content tweak to suggest a change page

jest.setup.js, src/moj/components/button-menu/button-menu.spec.js, src/moj/components/date-picker/date-picker.spec.js, src/moj/components/filter-toggle-button/filter-toggle-button.spec.js, src/moj/components/password-reveal/password-reveal.spec.js
Tidy up the includes/requires of the all the test files to ensure only necessary files are included, and update them have consistent setup.
=> test: refactor tests for consistency

jest.setup.js, package-lock.json, package.json, src/moj/components/button-menu/button-menu.spec.js, src/moj/components/date-picker/date-picker.spec.js, src/moj/components/filter-toggle-button/filter-toggle-button.js, src/moj/components/filter-toggle-button/filter-toggle-button.spec.js, src/moj/components/password-reveal/password-reveal.spec.js
Adds JS tests for the filter toggle component, and tidy up and improve the test setup a bit
=> Filter toggle tests

docs/_includes/arguments/interruption-card.md, docs/examples/interruption-card/index.njk, src/moj/components/interruption-card/template.njk
Adds in the arguments for the interruption card nunjucks macro
=> docs(interruption card): add nunjucks macro arguments

docs/examples/add-another/index.njk
Adding Figma link to documentation for 'Add another' component.
=> docs(add another): add figma link

package-lock.json, package.json, src/moj/components/search-toggle/search-toggle.js, src/moj/components/search-toggle/search-toggle.spec.js
Adds in tests for the search toggle (sub)component
=> test(search toggle): add tests for search toggle

docs/_includes/layouts/tabbed-content.njk
=> docs: update template

docs/service-patterns/apply.md
A new tab for stages and steps. Small amends elsewhere.
=> docs: amend apply service pattern

src/moj/components/sortable-table/sortable-table.spec.js
Adds tests for the sortable table component.
=> test(sortable table): add tests for sortable table component

src/moj/components/add-another/add-another.js, src/moj/components/add-another/add-another.spec.js
Add tests for the add another component
=> test(add another): add tests for add another component

jest.config.js, package-lock.json, package.json, src/moj/components/multi-file-upload/multi-file-upload.js, src/moj/components/multi-file-upload/multi-file-upload.spec.js
Adds tests for the multi file upload component.
=> Multi file upload tests

docs/_includes/macros/nav-list-item/template.njk, docs/assets/javascript/collapsible-nav.mjs, package-lock.json
Removes the use of CSS `:has` from within the side nav JS.
=> docs(side nav): update side nav to remove css :has for better browser support

views/community/pages/add-external-audit.njk, views/community/pages/check-your-answers.njk, views/community/pages/confirmation.njk
=> fixes from QA

docs/_data/env.js, docs/_includes/layouts/nav-only.njk, docs/_includes/layouts/partials/side-navigation.njk, docs/commnunity.md, docs/get-involved/index.md, docs/get-involved/submit-new-component.md, docs/nav.md, package-lock.json, views/common/base.njk, views/common/community-nav.html, views/common/homepage-nav.html, views/community/pages/base.njk
This PR generates the navigation as standalone HTML which can hopefully be imported into a layout within the community space to avoid having to renunjucks-ify a built html file.
=> docs: proof of concept for generating standalone nav html

docs/style-guide-updates.md
=> style(docs): fix lint errors in style guide markdown

views/common/base.njk
=> docs: update the js and css files included within the community spacek

docs/components/date-picker.md
=> Updating accessibility statement 

docs/accessibility.md, docs/help.md
=> docs: update DS mailbox

package.json
=> chore: move puppeteer to dev dependencies

docs/components/search.md, docs/examples/search/index.njk
=> docs: update search docs

.github/workflows/publish-package.yml
Rotating secrets for security.  Reducing permissions and attempting to use the admin permission only when necessary.
=> build: update tokens in guthub actions

app.js, helpers/check-your-answers.js, middleware/component-session.js, routes/add-component.js
Ensure that `template` and `pageData` are valid keys from the COMPONENT_FORM_PAGES object
=> Security fixes [5]

docs/components/badge.md, docs/components/filter.md, docs/components/notification-badge.md
=> docs: remove notification banner

app.js, config.js, helpers/check-your-answers.js, helpers/mockSessionData/sessionData.js, middleware/component-session.js, middleware/generate-documentation.js, package-lock.json, routes/add-component.js, schema/add-assistive-tech.schema.js, schema/add-external-audit.schema.js, schema/add-internal-audit.schema.js, schema/component-code-details.schema.js, views/common/homepage-nav.html, views/community/pages/accessibility-findings.njk, views/community/pages/add-assistive-tech.njk, views/community/pages/add-external-audit.njk, views/community/pages/add-internal-audit.njk, views/community/pages/check-your-answers.njk, views/community/pages/component-code-details.njk, views/community/pages/component-code.njk, views/community/pages/component-details.njk, views/community/pages/component-image.njk, views/community/pages/figma-link.njk, views/community/pages/figma.njk, views/community/pages/prototype-url.njk, views/community/pages/prototype.njk, views/community/pages/your-details.njk
This PR refactors the conditions config for determining the next page within `config.js`
The conditions are moved to their own key within the object.  This is in preparation to move the question labels and hints into this config object.
=> docs(contributions): Refactor routing conditions [1]

.github/ISSUE_TEMPLATE/TASK.md
=> docs: update task description

app.js, package-lock.json, package.json, routes/add-component.js
This PR adds in xss middleware to sanitize `req.body`, `req.headers` and `req.query` and `req.params`
=> docs(contributions): add xss middleware

app.js, helpers/previous-page.js, middleware/component-session.js, package-lock.json, package.json, routes/add-component.js
=> More security

helpers/check-your-answers.js, middleware/process-subission-data.js, routes/add-component.js, views/community/pages/your-details.njk
* Don't include details in the github submission unless user has given permission
* Fix file paths in PR - update component-code-details/1.txt to component-code-details-1.txt
* Put all text files into a submissions directory
* Fix confirmation page route
=> docs(contributions): don't include personal details in github submission

config.js, helpers/next-page.js, middleware/component-session.js, routes/add-component.js
=> Ensure dependent questions are answered

docs/style-guide-updates.md
Fix previous merge failing to deploy.
=> docs: run prettier

docs/get-involved/contribute.md
Replaced the google spreadsheet & form to Microsoft.
This is a placeholder till we go live with the contribution form incase we potentially get contribution.
- Are you changing functionality? [Copy the …
=> docs: update contribute page

docs/components/date-picker.md, docs/components/search.md
=> docs: update accessibility fix dates

docs/examples/badge-complete/index.njk, docs/examples/badge-urgent/index.njk, docs/examples/badge/index.njk
=> docs: update badge tab title

docs/_data/statusInfo.json, docs/_includes/layouts/partials/building-block-header.njk, docs/_includes/layouts/partials/page-header.njk, docs/_includes/macros/status-label/macro.njk, docs/_includes/macros/status-label/template.njk, helpers/mockSessionData/sessionData.js, middleware/generate-documentation.js, middleware/process-subission-data.js, routes/add-component.js, views/community/pages/check-your-answers.njk
=> Experimental component page

app.js, docker/nginx-preview.conf, middleware/component-session.js, routes/add-component.js, schema/component-code-details.schema.js
=> Add security and csp

docs/components/scrollable-pane.md
=> docs: fix grammar

.github/workflows/branch-preview-cleanup.yml
Ensure the express app service is also cleaned up on merging or closing a preview:active branch.
=> chore: cleanup express app service

docs/ethics/assessment.md, docs/ethics/design-ethical-services.md, docs/ethics/principles.md, docs/ethics/review.md
Requested changes made. To be reviewed.
=> docs: update ethics content

kubernetes-deploy-production.tpl
=> build: fix error in deployment yaml

docker/nginx-production.conf
=> docs: update nginx config to allow access to contribute url

docs/_data/env.js
=> docs: enable menu item for experimental components

docs/design-system-statuses.md
Updates to the status page statuses
=> docs: Status change content rebase

app/helpers/mockSessionData/sessionData.js, app/middleware/process-subission-data.js, app/middleware/process-submission-data.spec.js, app/views/community/pages/component-code-details.njk, docs/_includes/macros/status-label/template.njk, docs/stylesheets/components/_prose.scss
Fixes tab hover styling
Fixes case of code language on generated experimental component page
Increases max-height of img-container on experimental component page
=> docs: small snagging fixes after experimental component journey release

app/middleware/__snapshots__/generate-documentation.spec.js.snap, app/middleware/generate-documentation.js
* Adds curly quotes around component names in generated documentation page.
* fixes casing of component name in links
* updates the figma link text
=> Update figma content

renovate.json
=> chore: update renovate minimum release age

.github/workflows/deploy-production.yml, .github/workflows/playwright.yml, .github/workflows/publish-package.yml, .github/workflows/renovate.yml, .github/workflows/sass.yml
Add permissions blocks to all workflows
=> ci: add permissions blocks to github actions workflows

docs/ethics/design-ethical-services.md
additional bulletpoint on https://design-patterns.service.justice.gov.uk/ethics/design-ethical-services/
=> docs: update ethics guidance

docs/stylesheets/components/_vertical-nav.scss, package-lock.json
- align headings and nav items
- restyle headings
- adjust vertical spacing around dividers
=> style: fix side nav styling

playwright.config.js, tests/e2e/component-page.spec.js, tests/e2e/components.spec.js, tests/e2e/homepage.spec.js, tests/tsconfig.json, tsconfig.json
Adds tests for basic ds site functionality and checks component examples have initialised
=> test: add e2e tests for design system docs site
