- app/views/components/organisation-switcher/index.html
- app/views/index.html
- app/views/layouts/base.html
- src/components/_all.scss
- src/components/moj-organisation-switcher/README.md
- src/components/moj-organisation-switcher/_organisation-switcher.scss
- src/components/moj-organisation-switcher/macro.njk
- src/components/moj-organisation-switcher/template.njk
> Add organisation switcher

- app/views/components/currency-input/index.html
- src/components/moj-currency-input/README.md
Added the following:
- Links to guidance (MOJ Design System and MOJ Frontend)
- Links to dependencies (In this instance, to the GOV.UK Frontend hint, label and error message components)
- Examples (default example and one showing a different currency being injected)
- Attribute guidance (for the main container, currency, hint, label and error message objects)
> Update currency input documentation

- app/views/components/organisation-switcher/index.html
- src/moj/components/organisation-switcher/template.njk
#66 
Only display the organisation switcher link if a link object is
passed to the component.
This prevents an empty link tag being output to the source if there
is no link destination.
This change still supports the fallback text as long as a link `href`
is supplied.
It also updates the example to show how the component will look
without a change link and with the fallback link text.
This removes the ability to add HTML inside the link element. I can't see why we would want to accept HTML inside this particular element though and it felt like this implementation may have been copied from other components that may have a specific need for it. Where possible we should be limiting the amount of locations input can be marked as safe and displayed as HTML.
With this configuration:
```
{{ …
```
>  Update organisation switcher link logic

- src/moj/components/header/_header.scss
This bug was identified in issue #79 when being used in a Rails app. I have also ran into this issue but when importing via webpack using `sass-loader`.
In `_header.scss` the colour value black was not in quotes which seemed to be causing parsing errors.
Webpack and rails preprocessors appear to be stricter than gulps and so it causes an error while parsing
I have amended the value black to be in quotes as all other colours are in the SCSS files.
Move all colours to a colour palette variable file to be referenced instead
None I can think of
* I cloned the repo and ran npm link to connect it to my webpack project.
* I still got the same error
* I changed the value to be in quotes
* Retried with webpack and the error disappeared and the SCSS files were processed out to CSS correctly
Fixes a …
> Fixes issue #79 with colour value not wrapped in quotes

- gulp/build-javascript.js
- package-lock.json
- package.json
N/A but [discussed on Slack](https://mojdt.slack.com/archives/CH5RUSB27/p1570200776007000)
Currently the JavaScript module is exposed as a global variable, and may be used by including the `all.js` file and accessing `window.MOJFrontend`. This doesn't support use cases with bundlers, where the package needs to export something.
Fortunately, there is a JavaScript design pattern called "[Universal Module Definition](https://riptutorial.com/javascript/example/16339/universal-module-definition--umd-)" (UMD) which allows the module to support various different export styles depending on the context it's used in. It only adds a few extra lines to the file and is backwards compatible. It is also [currently used](https://github.com/alphagov/govuk-frontend/blob/master/tasks/gulp/compile-assets.js#L …
> Output JavaScript as UMD

- docs/installation/installing-with-npm.md
The `installing-with-npm` documentation refers to a variable called `$moj-image-url-function`. This variable is not referenced anywhere and setting it does nothing.
- Remove `$moj-image-url-function` variable from the docs, because setting it has no effect
> Remove misleading reference to $moj-image-url-function

- src/moj/components/pagination/_pagination.scss
This fixes bug #88
This ensures that the `moj-pagination__result` child element of the `moj-pagination` class have an explicit font-size so will be shown to the user.
I've applied the same rule already used for `moj-pagination__item` to ensure consistency between the child elements.
I didn't identify any suitable alternatives.
If a user was overwriting the font size of pagination elements with utility classes, they'd now also have to add a utility class to `moj-pagination__result` (rather than falling back on the GOV.UK Design System classes)
I can't identify any regressions that mmight be caused by this and could be tested. 
- Fixed an issue where the pagination results text was hidden in wide browsers
> Add font specification to pagination results

- app/assets/sass/application.scss
- app/views/components/messages/index.html
- src/moj/components/header/_header.scss
- src/moj/components/pagination/_pagination.scss
- src/moj/components/primary-navigation/_primary-navigation.scss
- src/moj/components/sub-navigation/_sub-navigation.scss
Fixes #95 - MOJ Header component display issues
Updated MOJ Header styles so that it displays correctly when `$govuk-global-styles` is not set.
N/A
N/A
Tested with `$govuk-global-styles` enabled and disabled in order to ensure that it displays and behaves the same.
Updated MOJ Header styles so that it displays correctly when `$govuk-global-styles` is not set.
> Corrected MOJ header styles

- app/views/components/cookie-banner/index.html
- app/views/index.html
- app/views/layouts/base.html
- src/moj/components/_all.scss
- src/moj/components/cookie-banner/README.md
- src/moj/components/cookie-banner/_cookie-banner.scss
- src/moj/components/cookie-banner/macro.njk
- src/moj/components/cookie-banner/template.njk
Relates to issue #92 
This change adds a new Cookie Banner component. 
It does not contain any javascript currently. This component is purely for design purposes so that different projects can align on look and feel.
A separate pull request can be done post this to add a dynamic javascript implementation.
Previous designs have had 2 primary buttons in the header. This uses 1 primary and 1 secondary as per the GDS rules so it doesn't cause confusion to the user.
Some existing designs have a darker background, this has been removed to help increase colour contrast in the design.
None I can think of
To test we have implemented the design on the new Use a LPA service. It also exists in the CICA website. The design was taken from there and classes amended to fit the MoJ namespace.
I have used …
> Added cookie banner component

- .circleci/config.yml
- .releaserc.json
- README.md
- commitlint.config.js
- package-lock.json
- package.json
- package/README.md
- package/package.json
To add circleci to the project so that building and publishing of the package is done automatically without manual intervention.
This also includes the addition of commitizen to make commits versionable for the versioning of the packages/releases.
This saves time and removes human blockers to the release process. It also removes any skill gaps for being able to make changes and publishing these easily.
Require people to use the semvar commit syntax. I have added in commitizen to make this easier and husky to help lint messages before being able to commit to mitigate this. Adding this to the README will also give clearer guidance.
Ran the dry-run command for semantic-release to see how it would handle a publish. All looked good, however it will be a test on merging to master to be …
> ci: added commitizen, semantic-release and circleci

- app/views/components/rich-text-editor/index.html
- src/moj/all.js
Include "moj" in prefix to avoid collisions with other libraries.
> Fix rich-text-editor attribute prefix

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- package.json
- package/README.md
- package/package.json
The linked email address isn't operated as a support channel and shouldn't be advertised to users.
Instead, direct them to https://moj-design-system.herokuapp.com/get-in-touch where up-to-date contact details can be found.
Fixes #148
> Replace email with contact URL

- src/moj/components/add-another/_add-another.scss
* Fill out the template below. Maintainers are free to close any pull requests that do not include enough information, at their discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at https://github.com/ministryofjustice/moj-frontend/tree/master/.github/PULL_REQUEST_TEMPLATE.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see https://github.com/ministryofjustice/moj-frontend/tree/master/CONTRIBUTING.md#pull-requests.
#152 
Add an extra CSS rule in the `.moj-add-another__title` class that clears floats on a sibling …
> fix(add-another): clear floating legend

- src/moj/components/ticket-panel/_ticket-panel.scss
The default ticket panel currently has a black border because `border-left-color` is not specified. This change instead makes it transparent, so that the border only appears if you add one of the variant classes (e.g. `.moj-ticket-panel__content--red`).
This means that default ticket panels have an extra 4px padding on the left, but this doesn't stand out visually and ensures that the text aligns between plain and colourful ticket panels.
> Make default ticket panel have no border

- docs/examples/page-header-actions/index.njk
I accidentally missed a quote mark and a comma, meaning the docs cannot render
> Fix syntax error

- package.json
When running CI tests, build the docs to ensure it can happen without error
> ci: test docs can build in CI

- docs/components/tag.md
- Add notification banner to communicate this component us on the GOV.UK Design System
- Remove duplicate guidance which is already on the GOV.UK Design System, leaving just the additional colours.
- Change where people are directed to contribute from the MOJ GitHub repo to the GOV.UK Design System
--- | ---
|![Screenshot 2021-06-23 at 09 16 06](https://user-images.githubusercontent.com/6122118/123063337-38ee5300-d405-11eb-8928-62ea80f4c2b4.png)|![Screenshot 2021-06-23 at 09 16 12](https://user-images.githubusercontent.com/6122118/123064218-fe38ea80-d405-11eb-8c8a-c637e6d8cf78.png)|
Users can access the MOJ additional colours of the Tag component which is not on the GOV.UK Design System, and navigate to the GOV.UK Design System for guidance on usage and to contribute.
> docs: remove duplicate tag guidance

- docs/_includes/layouts/component.njk
- docs/components/badge.md
- Group components in the navigation into four categories: Structure, Navigation, Forms, Content 
- Order components within categories based on how they may be ordered on the page where possible, instead of alphabetically
**Also in this PR**
- Add notification banner to the Badge component to communicate there is a similar component (Tag) in the GOV.UK Design System which should be considered. 
--- | ---
|![ministryofjustice github io_moj-frontend_components_(iPad Pro) (1)](https://user-images.githubusercontent.com/6122118/123254330-71199280-d4e6-11eb-8b78-ce1823629d7c.png) |![localhost_8080_components_(iPad Pro) (1)](https://user-images.githubusercontent.com/6122118/123254367-7a0a6400-d4e6-11eb-8788-21c33135ca77.png) |
|![ministryofjustice github …
> Add component categories

- docs/_includes/layouts/component.njk
- docs/components/archived-components.md
- docs/components/currency-input.md
- docs/components/index.md
- docs/components/tag.md
- Update the term 'Retired components' to 'Archived components'
The term 'archived components' has been referenced from HMRC Design Patterns as a better term for components which should no longer be used.
--- | ---
|![ministryofjustice github io_moj-frontend_components_retired-components_(iPad Pro)](https://user-images.githubusercontent.com/6122118/123411546-7c34f700-d5a8-11eb-9acd-61a538281844.png) |![localhost_8080_components_archived-components_(iPad Pro)](https://user-images.githubusercontent.com/6122118/123411598-87882280-d5a8-11eb-9f1a-ec6a6a002ea0.png) |
Users will be able to see archived components, when they were archived and what they should use instead.
> docs: update term retired to archived components

- .github/workflows/docs.yml
- docs/_includes/layouts/partials/navigation.njk
We're now hosted on a root domain, not in a subdirectory, so don't want links to include a path prefix
This also fixes #176 by changing how the primary navigation pages are highlighted
> build: remove path prefix

- docs/examples/add-another/script.js
- package/moj/all.js
- package/moj/components/add-another/add-another.js
- src/moj/components/add-another/README.md
- src/moj/components/add-another/add-another.js
This was identified by @owen-bennett123 in #185
When a text input has affixes, it is wrapped in a `.govuk-input__wrapper` div, meaning its label is
no longer adjacent. This caused the Add anotehr component to fail, because it couldn't find the
input's label and update its for/id link.
I've added a new strategy for finding the label: if it's not the parent or adjacent, then JavaScript
identifies it by searching for a label whose `for` attribute is the ID of the original input.
This should not introduce any regressions because the previous strategies are still in place and
prioritised: the new strategy will only be used if nothing was found, which would have previously
resulted in the application crashing.
I also did some cleanup:
- Removed an unnecessary `script.js` from the Add another …
> fix(add-another): find labels of affixed text inputs

- docs/components/index.md
- docs/components/notification-badge.md
- docs/patterns/task-list.md
- Remove duplicate guidance on Notification banner component which exists on HMRC Design Patterns
- Add banner with link to HMRC Design Patterns and the GOV.UK Design System backlog
It was felt that the previous iteration using the structured headings taken from the GOV.UK Design System made the component look more 'finished' than it is, and didn't clearly reflect that there is only a small amount of guidance on the component to date. 
To better reflect the component as a work in progress in order to encourage contribution, and to reduce the overhead of maintaining guidance that exists elsewhere, it was agreed to remove duplicate guidance and reduce the page to the minimal information. 
The method of contribution will be added in the future.
--- | --- …
> Update notification badge documentation

- docs/components/add-another.md
- docs/components/badge.md
- docs/components/banner.md
- docs/components/button-menu.md
- docs/components/currency-input.md
- docs/components/filter.md
- docs/components/form-validator.md
- docs/components/header.md
- docs/components/identity-bar.md
- docs/components/messages.md
- docs/components/multi-file-upload.md
- docs/components/multi-select.md
- docs/components/notification-badge.md
- docs/components/organisation-switcher.md
- docs/components/page-header-actions.md
- docs/components/pagination.md
- docs/components/password-reveal.md
- docs/components/primary-navigation.md
- docs/components/rich-text-editor.md
- docs/components/search.md
- docs/components/side-navigation.md
- docs/components/sortable-table.md
- docs/components/sub-navigation.md
- docs/components/tag.md
- docs/components/timeline.md
- docs/index.md
- docs/patterns/filter-a-list.md
- docs/patterns/get-help.md
- docs/patterns/task-list.md
- docs/patterns/upload-files.md
The following changes have been made with the primary motivation to reduce cognitive load:
- Remove duplicate installation guidance on components and patterns which exists on the landing pages
- Shorten headers referencing HMRC Design Patterns
- Remove empty sections until further information is added, for example 'Research' and 'Contribute'
--- | ---
|![design-patterns service justice gov uk_components_header_(iPad Pro) (1)](https://user-images.githubusercontent.com/6122118/123943651-47ec7c80-d994-11eb-9aa5-b688f482312a.png) |![localhost_8080_components_header_(iPad Pro)](https://user-images.githubusercontent.com/6122118/123943701-533fa800-d994-11eb-829a-1ec6d4c58025.png) |
Users will be able to more clearly see the how developed the components and patterns guidance is.
> Remove duplicated installation guidance

- docs/_includes/layouts/component.njk
The following changes have been made using the [NHS Design System](https://service-manual.nhs.uk/design-system/components) as reference, in order to improve component navigation
- Rename `Content` to `Content presentation` (so as not to be confused with writing)
- Rename `Forms` to `Form elements` (to be clearer it is parts of forms)
- Merge `Structure` and `Navigation` (components like `Header` are seen as a form of navigation)
- Reorder, moving `Form elements` to the top (as they are the most used components)
--- | ---
|![design-patterns service justice gov uk_components_notification-badge_(iPad Pro) (1)](https://user-images.githubusercontent.com/6122118/123982769-37033180-d9bb-11eb-898f-490cd30cd668.png) |![localhost_8080_components_notification-badge_(iPad Pro) …
> docs: update component categories

- docs/_includes/layouts/patterns.njk
- docs/patterns/question-pages.md
- Add 'Question pages' pattern, which communicates the process in MOJ for deciding on whether to use one or multiple questions per page. 
This pattern utilises existing GOV.UK guidance and content, reducing the overhead for maintenance.
|Question pages pattern |
--- 
|![localhost_8080_patterns_question-pages_(iPad Pro)](https://user-images.githubusercontent.com/6122118/124134869-316d2080-da7b-11eb-9eaf-aa7946678119.png) |
Users will be able to read and follow guidance on questions pages and when to use multiple questions per page.
> docs: add question pages pattern

- docs/index.md
Related issue: https://github.com/ministryofjustice/moj-frontend/issues/211
Update the 'Get started' page with:
- links to the department design systems and community backlog
- links to GitHub Discussions for contributing
To make the process clearer on what users should do first before using the MOJ Pattern Library, and what they should do if they want to contribute.
This guidance utilises an existing list of department design systems, reducing the overhead for maintenance.
--- | ---
|![design-patterns service justice gov uk_(iPad Pro)](https://user-images.githubusercontent.com/6122118/124633395-25b79a80-de7d-11eb-8d5e-d7f6719fc25a.png) |![localhost_8080_(iPad Pro) (1)](https://user-images.githubusercontent.com/6122118/124633453-32d48980-de7d-11eb-9cfe-7a6165af296b.png) …
> docs: update get started links

- docs/components/filter.md
- docs/components/multi-select.md
- docs/patterns/add-to-a-list.md
- docs/patterns/question-pages.md
Add discussion links to these pages:
- Filter
- Multi select
- Add to a list
- Question pages
Users will be able to navigate to discussion pages on these components and patterns.
> docs: add discussion links to pages

- README.md
Update links to documentation and contact in the README, this is reproduced on other services like [our NPM page](https://www.npmjs.com/package/@ministryofjustice/frontend) so needs to be up-to-date
> docs: update links in README

- README.md
- docs/_includes/layouts/base.njk
- docs/get-started/production.md
- docs/get-started/prototyping.md
- docs/get-started/setting-up-javascript.md
- package/README.md
Update remaining instances of "MOJ Design System" to "MOJ Pattern Library" to solidify new name. Notably this includes the title suffix.
> docs: rename to "MOJ Pattern Library"

- docs/components/filter.md
- link on the Filter component to the GOV.UK community backlog is going to the wrong issue
- update the link to the correct GitHub issue
- the Filter component will have the correct link to the GOV.UK community backlog GitHub issue.
> docs: fix govuk backlog link in filters

- src/moj/components/add-another/_add-another.scss
The GOV.UK Design System extends buttons to 100% width on small screens. The Add another
component's "Remove" button is absolutely positioned, so it covers up content when it's at 100%
width.
This change shrinks the button back down to `width: auto`, so that it's only as wide as the text
and any content "underneath" can be seen.
I've also added right padding to the title so that it wraps before going underneath the remove
button.
This does reduce the clickable area for the button, which may make it harder for touchscreen users,
however there should not be any other clickable targets nearby, so users are unlikely to press the
wrong thing.
| Before | After |
|--------|-------|
| ![Screenshot 2021-09-15 at 10 59 21](https://user-images.githubusercontent.com/100852/133413561-1fd19d6b-8abf-4966 …
> fix(add-another): shrink remove button

- README.md
- docs/_includes/layouts/partials/contact-panel.njk
- docs/components/index.md
- docs/get-started/deploying-your-prototype.md
- docs/patterns/index.md
- package/README.md
Update the name of the support channel in Slack, and add a more helpful GitHub link
> docs: fix Slack channel name and GitHub link

- docs/_includes/layouts/patterns.njk
- docs/patterns/case-list.md
- Add 'Case list' pattern, which communicates the pattern for making pieces of information about a case easier to scan, prioritise and action for users.
- Add link to the GitHub discussion for others to add to and iterate on the pattern
This pattern doesn't include working code, only screenshots and guidance. This pattern utilises existing GOV.UK components in describing how to use the pattern, reducing overhead and maintenance. 
|Case list pattern |
|---| 
|![localhost_8080_patterns_case-list_(iPad Pro) (2)](https://user-images.githubusercontent.com/6122118/134193811-d013c2f0-9990-4428-b95b-44721eb84c6b.png) |
Users will be able to read and follow guidance on the 'Case list' pattern.
> Add case list pattern

- docs/_includes/arguments/sub-navigation.md
- src/moj/components/sub-navigation/template.njk
Rather than opening an issue, I thought I'd use this PR for any necessary discussion, because the code change itself is small.
[hmpps-manage-supervisions](https://github.com/ministryofjustice/hmpps-manage-supervisions) recently underwent a [DAC accessibility review](https://digitalaccessibilitycentre.org/). One of the issues they brought up in their audit was the lack of an `aria-label` on the sub navigation element in the app.
This PR sets a default `label` property on `mojSubNavigation` of "Secondary navigation region".
It looks like this in the accessibility inspector:
`label` could be made into a required property and produce a build error when it's not specified. This would break most apps that update to the latest version of the design system. I think silently filling in a sensible …
> Add a default aria-label for sub navigation component

- src/moj/components/badge/template.njk
- src/moj/components/banner/template.njk
- src/moj/components/button-menu/template.njk
- src/moj/components/filter/template.njk
- src/moj/components/header/template.njk
- src/moj/components/identity-bar/template.njk
- src/moj/components/messages/template.njk
- src/moj/components/multi-file-upload/template.njk
- src/moj/components/notification-badge/template.njk
- src/moj/components/page-header-actions/template.njk
- src/moj/components/primary-navigation/template.njk
- src/moj/components/progress-bar/template.njk
- src/moj/components/sub-navigation/template.njk
- src/moj/components/ticket-panel/template.njk
- src/moj/components/timeline/template.njk
Almost all MoJ design system components do not put correct whitespace around custom attributes in the nunjucks template.
For instance, https://github.com/ministryofjustice/hmpps-incentives-ui/blob/b8892793247cad8af2c2494802ce839e3abdaf99/server/views/pages/analytics/graph-layout.njk#L5-L24 renders as:
```html
<nav class="moj-sub-navigation govuk-!-display-none-print" aria-label="Incentive data navigation">
<ul class="moj-sub-navigation__list">
<li class="moj-sub-navigation__item">
<a class="moj-sub-navigation__link" aria-current="page" href="/analytics/incentive-levels"data-qa="incentive-levels">Incentive levels</a>
</li>
<li class="moj-sub-navigation__item">
<a class="moj-sub-navigation__link"  href="/analytics/behaviour-entries"data-qa="behaviour-entries">Behaviour entries</a>
</li>
<li …
```
> fix(components): ensure that custom attributes get a space inserted before each one

- src/moj/components/pagination/template.njk
`id` and `aria-labelledby` attributes were swapped resulting in screen readers not reading out the pagination label
Swapped the attributes
N/A
None
Tested with NVDA
N/A
> fix attributes in pagination's template.njk

- src/moj/components/pagination/template.njk
Use aria-label to provide more descriptive label for pagination page links
Fix label content for previous/next links
Use aria-current to highlight that the current page is selected
Use ellipsis rather than three dots
Fixes #161
> fix(pagination): improve accessibility of pagination component

- src/moj/components/password-reveal/password-reveal.js
Retain button text of Show/Hide but announce it as Show password/Hide password for screen readers
Fixes #55
> fix(password-reveal): improve screenreader labels

- src/moj/components/multi-file-upload/multi-file-upload.js
Use `<div>` instead of some lone `<dd>`s. This isn't semantic HTML so we should stop pretending it is.
> fix(multi-file-upload): remove semantic HTML

- docs/_includes/layouts/component.njk
- docs/components/archived-components.md
- docs/components/form-validator.md
- docs/components/rich-text-editor.md
Archive the Form validator and Rich text editor components
Whilst we will continue to support them, they are no longer recommended
Both components have some fairly major accessibility concerns, and we don't have the capacity to support them. There are also _much_ better libraries available for both that are better featured, better supported and fully accessible.
> feat: archive deprecated components

- src/moj/components/banner/template.njk
Banner components are given the region role and an appropriate label to identify them.
The label is taken from, in order or priority:
- The `iconFallbackText` label, if set
- The type of banner (e.g. "success", "warning", "information")
- The word "banner"
I also removed the visually-hidden insertion `iconFallbackText` to avoid duplication: if provided, this is now the region's label.
The only possible regression I can think of is if people have written `iconFallbackText` to flow as a full sentence with the text content, which would now be broken up. If someone strictly needed that behaviour, they can simply append the content to `html`.
> fix: markup Banner components as regions

- docs/examples/timeline/index.njk
- src/moj/components/search-toggle/search-toggle.js
- src/moj/components/search-toggle/search-toggle.scss
- src/moj/components/timeline/_timeline.scss
Rather than embedding SVGs as background images, use them inline. This allows them to keep their parents' fill colour, so they can always adapt to match the text.
When forced color mode is active (e.g. Windows High Contrast mode), we need to force the fill colour to match the context (i.e. text or link colour), otherwise it doesn't pass through properly on Windows.
This is an accessibility enhancement as it means that users who use tools like high-contrast mode to force changes in background and foreground colours will continue to be able to see iconography. Without it, icons are invisible if they're the same colour as the forced background colour.
Fixes #162
> fix: use inline SVGs

- docs/components/pagination.md
Now that the GOV.UK Design System has a Pagination component, nudge people towards it. In the future we'd hope to deprecate our Pagination component to reduce duplication.
> docs: nudge users towards GDS Pagination component

- assets/sass/application.scss
- assets/sass/components/flex-container.scss
- docs/_includes/example.njk
- docs/_includes/layouts/component.njk
- docs/_includes/layouts/get-started.njk
- docs/_includes/layouts/partials/contact-panel.njk
- docs/_includes/layouts/partials/footer.njk
- docs/_includes/layouts/partials/header.njk
- docs/_includes/layouts/patterns.njk
- docs/_includes/layouts/plain.njk
- docs/accessibility.md
- docs/patterns/index.md
Fixing the issues [identified in testing](https://docs.google.com/spreadsheets/d/1j7Ms7OcbMyEt4-AlZ-SGpUIl8XN3ylyFJixHQW9Z1XE/edit#gid=1536858132) (as much as possible)
Fixes:
- Adds a skip link before the site header
- Removes the link from "Ministry of Justice" (only "Pattern Library" should link to the homepage)
- Size of "Need help?" header now matches header level
- iframe examples now have `title` attribute set (rather than `aria-label`, which was intended to do the same but isn't the standard)
- "Back to top"  button scrolls with the page
- Crown copyright link is fixed
- Privacy policy removed as we don't have one
- Fix spelling of channel name on Patterns page
> docs: fix accessibility and usability issues

- .eleventy.js
- .releaserc.json
- docs/get-started/prototyping.md
- package/package.json
Load version from package info, rather than hard-coding it
Also, ensure package is updated by CI release processes
> docs: load version into docs dynamically

- docs/components/password-reveal.md
- src/moj/components/password-reveal/password-reveal.js
Automatically set spellcheck attribute to false to protect users' passwords from being sent to remote spellcheck services.
Chrome and Edge [both send plain text to their servers for spellchecking](https://www.bleepingcomputer.com/news/security/google-microsoft-can-get-your-passwords-via-web-browsers-spellcheck/). Setting the `spellcheck` attribute to `false` prevents this behaviour.
> feat(password-reveal): set spellcheck attribute to false

- docs/examples/patterns/filter-a-list/index.njk
- src/moj/objects/_scrollable-pane.scss
The `.scrollable-pane` class is supposed to add shadows to indicate that its contents are scrollable, but it is not suitably dynamic.
This CSS uses [scroll shadows](https://www.bram.us/2019/10/24/pure-css-scroll-shadows-vertical-horizontal/) to make the shadows dynamically appear on the left and right when there's overflow content there.
If there's no overflow content, or the container is scrolled all the way to one side, the shadows are hidden.
I removed the `.moj-scrollable-pane__wrapper` class because it's unnecessary.
> fix(scrollable): fix CSS shadow effect

- .github/workflows/main.yml
- package-lock.json
via `npm upgrade socket.io-parser`
> chore: bump socket.io-parser to 4.0.5

- package-lock.json
To upgrade `socket.io-parser` to ≥4.2.1. `npm upgrade socket.io && npm upgrade socket.io-client`
> chore: bump `socket.io` and `socket.io-client`

- .eleventy.js
- .github/workflows/cd-staging.yaml
- Dockerfile
- docs/_data/env.js
- docs/_includes/layouts/partials/header.njk
- kubernetes-deploy-staging.tpl
Provides a preview environment at https://moj-frontend-staging.apps.live.cloud-platform.service.justice.gov.uk/ of whatever is deployed to the `staging` branch.
The staging environment gets a garish banner to inform people that it's not the real documentation.
Next step: auto-push to staging when someone adds a label to a PR
> chore: add staging environment

- docs/_includes/layouts/component.njk
- docs/components/scrollable-pane.md
- docs/examples/scrollable-pane/index.njk
- package-lock.json
We've had this component for a while, but never documented it.
[Preview environment](https://moj-frontend-fgw467dml-vercel-gregtylerco.vercel.app/components/scrollable-pane)
> docs(scrollable-pane): add documentation for scrollable pane component

- .github/workflows/deploy-staging.yaml
- .github/workflows/tag-staging.yml
- docs/_includes/layouts/partials/header.njk
If the `staging:request` label is added, the PR will be pushed to `staging` and deployed to the staging env. If any other PRs are currently deployed, their label will be removed.
> chore: auto-deploy to staging when label added to PR

- .github/workflows/tag-staging.yml
Rather than pushing to `staging` branch and triggering a build job (which doesn't work), push straight to Kubernetes from HEAD.
> chore: auto-stage PRs by pushing straight to Kubernetes

- README.md
* Adds NPM badges to signify version and usage of the library.
* Replaces the old build status badge for CircleCI to Github Actions
Updates badges on README
> docs(readme): add NPM Badges and Github workflow status

- src/moj/objects/_scrollable-pane.scss
postcss-calc isn't happy about the `calc()` function without a `var()` (see #433). This new syntax is compatible and produces the same output in our distributed file.
> fix: use syntax compatible with postcss-calc

- docs/components/badge.md
Added a short sentence to tell HMPPS designers that the badge should only be used to show risk information.
Also changed 'Her Majesty's...' to 'His Majesty's...'
- Are you changing functionality? [Copy …
> Added HMPPS-specific guidance

- package-lock.json
- src/moj/components/sortable-table/sortable-table.js
https://github.com/ministryofjustice/moj-frontend/issues/441
This fixes the above issue by updating the finder in the `sort` function, which looks for a table cell OR a table header within the rows to ensure the index is correct.
N/A
N/A
Allow sortable tables to sort the correct column when the table rows have headers.
> Fix sortable tables for row headers

- renovate.json
To reduce noise when we get lots of dependency updates at the same time.
> chore: perform patch/minor updates in one PR

- docs/get-started/prototyping.md
- gulp/build-javascript.js
- gulp/jquery/scope.js
- gulpfile.js
- package/README.md
- package/govuk-prototype-kit.config.json
- src/moj/init.js
Allow the Pattern Library to automatically be available in the Prototype Kit when installed.
This requires producing a file with jQuery bundled (`all.jquery.min.js`) and an init file (`init.js`). When loaded into the Prototype Kit they automatically initialise all the components.
Update the documentation to explain that no further steps are necessary.
Fixes #465 and alphagov/govuk-prototype-kit#1823
> feat(prototype): better support for GOV.UK Prototype Kit

- renovate.json
By default it uses `fix` for production dependencies, but the `package.json` file only affects the docs site and semantic versioning affects the distributed package. So any changes to root dependencies, even production ones, just count as a build chore.
> build: use `build` for Renovate semantic versioning

- docs/get-started/prototyping.md
Prompt users to check they are using the latest versions of npm when updating the version of MOJ Frontend
> docs: check npm version when upgrading

- docs/examples/filter/index.njk
- src/moj/components/filter/template.njk
Currently it isn't possible to change the behaviour of the filter "Apply filters" button without externally selecting it using an imprecise address, such as `.moj-filter__options button`.
Although there are workarounds (such as wrapping the component in a form and hooking in to its submit event), it would be helpful to future users to provide a more direct way of changing the button's behaviour.
This adds the ability to directly set the filter component's "Apply filters" button attributes using the filter macro's parameters.
Alternative approaches would be to give the button a unique ID, or to specifically allow the click event to be set. This approach allows greater flexibility, and so hopefully caters for more use cases.
If users have previously unsuccessfully set the …
> fix(filter component): add filter submit attribute params to allow customisation of button

- src/moj/components/filter/template.njk
https://github.com/ministryofjustice/moj-frontend/issues/486
Added the ability to override the filter component's 'Apply filters' text using the newly-added `submit` section of the component's parameters.
This text could be updated externally using JavaScript or similar, but this allows the users to configure it from within the application's parameters.
Conceivably this functionality could be used to add a less descriptive or misleading description, but that would be an issue for the user themselves.
The filter example was updated to verify this functionality locally, but updating the button description in the documentation permanently seemed to present the option as mandatory.
Added the ability to override the filter component's 'Apply filters' button text.
> feat(filter component): add parameter for apply filters button text

- .github/workflows/tag-staging.yml
- kubernetes-deploy-staging.tpl
As per [Deprecating long-lived credentials for container repositories](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html).
> Update deployment workflow to replace use of long-lived credentials

- .github/workflows/tag-staging.yml
In the step above it's written to kubernetes-deploy-staging.yaml, not kubernetes-deploy.yaml
> build: fix location of k8s deploy file

- package/govuk-prototype-kit.config.json
Add metadata to plugin configuration.  The prototype kit team are working on new pages inside "Manage Prototype" which will display additional information about plugins.  The contents of this PR adds this information to the plugin config file.
- Added additional information to be shown in the prototype kit plugin page for this project
> docs(plugin configuration): add metadata to plugin configuration to be consumed on plugin pages

- docs/_includes/layouts/community.njk
- docs/community/contribute.md
- docs/community/criteria.md
**Description of change**
Inclusion of a contribution process and guidance on how to contribute into the MOJ Design System.
> docs(contributions): contribution process and criteria

- .github/workflows/tag-staging.yml
- Dockerfile
- docker/htpasswd
- docker/nginx.conf
This will avoid the staging environment being indexed by search engines
The username/password are published publicly on the PR because they're not secret
> docs: add password for staging environment

- docs/_includes/layouts/base.njk
- docs/_includes/layouts/home.njk
- docs/_includes/layouts/partials/get-help.njk
- docs/_includes/layouts/partials/header.njk
- docs/_includes/layouts/partials/suggest-a-change-and-help.njk
- docs/community/contribute.md
- docs/community/criteria.md
- docs/community/help-and-feedback.md
- docs/community/index.md
- docs/community/roadmap.md
- docs/community/suggest-a-change.md
- docs/community/users-and-data.md
- docs/components/archived-components.md
- docs/components/index.md
- docs/cookies.md
- docs/get-started/deploying-your-prototype.md
- docs/get-started/index.md
- docs/get-started/installing-compiled.md
- docs/get-started/installing-with-npm.md
- docs/get-started/our-approach.md
- docs/get-started/production.md
- docs/get-started/prototyping.md
- docs/get-started/setting-up-javascript.md
- docs/get-started/supporting-internet-explorer-8.md
- docs/index.md
- docs/patterns/index.md
The Ministry of Justice acronym is MoJ but it has been implemented as MOJ across the public site. This change replaced MOJ with MoJ.
> docs(moj to moj): decapitalising the o in MOJ

- docs/examples/header/index.njk
Version of the Header component created in Figma. Link to Figma included on the Header component page.
> docs: adding figma link for header component

- docs/_includes/layouts/patterns.njk
Page was dropped from navigation a while ago but still exists, this adds the nav back in.
> docs: add link to Upload files pattern

- src/moj/components/filter-toggle-button/filter-toggle-button.js
The container wasn't being wrapped in a jQuery tag, meaning the button wasn't properly appended to the DOM.
Use the jQuery-wrapped container instead.
> fix(filter toggle button): ensure button appears

- docs/pages/case-list.md
Broken links found on https://design-patterns.service.justice.gov.uk/pages/case-list/. Link issues resolved to direct to the filter component and the filter a list pattern, and resolving a broken link to the GOV Design System.
> docs(case list page): resolving broken links on case list page

- package-lock.json
- package.json
Cloning the repository and attempting to run all tests (`npm test`) produces errors linked to `gyp` and `node-sass`. 
Given the [`node-sass` library is deprecated](https://www.npmjs.com/package/node-sass), the official recommendation is to use the `sass` library instead. 
This change fixes issues with running all tests.
This should enable contributing developers to run tests locally.
> test: use sass instead of deprecated node-sass

- kubernetes-deploy-production.tpl
Removes the default cloudplatform url that we don't need from the kubernetes ingress.
> build(deployment): remove default cloudplatform site

- .github/workflows/deploy-production.yml
- kubernetes-deploy-production.tpl
This PR adds increases the number of pods, and also specifies a pod disruption policy that ensures at least one pod is always available.
> build(deployment): increase replicas and set pod disruption policy

- src/moj/components/date-picker/date-picker.js
fix #751
Prevent double-initialization of the component by adding a `data-initialized` attribute onto the `$module` after the `init()` method has run.  The `init()` method then checks for the presence of the attribute and aborts if it is present.
> fix(datepicker): prevent double initialization on datepicker components

- docs/examples/date-picker-leading-zeros/index.njk
- src/moj/components/date-picker/date-picker.js
added `return` statements to `setLeadingZeros` method to prevent calling `toLowerCase` on a boolean value.
fix #753
> fix(datepicker): fix issues with leadingZeros config option

- package-lock.json
- package.json
- src/moj/components/date-picker/date-picker.js
- src/moj/components/date-picker/date-picker.spec.js
This PR adds tests for all functionality of the datepicker with default config options. This includes keyboard navigation and axe accessibility checks.
During testing a couple of small issues were found and fixed:
* Date was initialized with an odd format order causing issues during testing
* Calculation of the first and last day of the week was incorrect when the last day of the week was a Sunday
* We were using `aria-selected` to mark the currently selected day, however `aria-selected` is not permitted on buttons, so changed to using `aria-current="date"` instead.
> Datepicker tests

- src/moj/components/button-menu/_button-menu.scss
- src/moj/objects/_button-group.scss
without js the alignment of the button menu items in a button group was not right.
Before:
After:
> fix(button menu): small tweak to fix alignment within an moj-button-group

- src/moj/components/action-bar/_action-bar.scss
The updates to the button menu caused the alignment of the buttons in the action bar component for filtering to be misaligned. This is a simple fix to ensure the buttons are aligned.
> fix(action bar): adjust alignment of filter toggle button when next to menu button

- docs/assets/javascript/collapsible-nav.js
in the side nav js the `openItems` getter did not account for whether the "open" item actually had children to be open.
This PR updates the querySelector to ensure the open item is also a collapsible item
(i.e. it has a nested `ul`)
Also added some extra safety in the `open` and `close` methods by returning early if the `$button` or `$list` elements are not present.
> docs(side nav): fix for top level items with no children

- docs/components/add-another.md
We noticed there was still a reference to "Her Majesty" in the documentation. This has been updated to "His Majesty".
We noticed there was still a reference to "Her Majesty" in the documentation. This has been updated to "His Majesty".
> Tiny change to fix a "Her Majesty" to "His Majesty"

- docs/_includes/layouts/partials/side-navigation.njk
- docs/assets/javascript/collapsible-nav.js
- package-lock.json
Our current sidenav custom element, applies incremental ids to each collapsible item within it starting with `collapsible-nav-0`
If there are multiple `<moj-collapsible-nav>` elements on a page, each starts applying ids from 0, which results in duplicate ids on the page.
This PR fixes this issue, by applying either a dynamic, timestamp-based id to each instance of the component, or by allowing the user to manually set an id on the custom element, and using this id as a prefix for the child collapsible nav elements.
> docs(side nav): fix duplicate id issue on collapsible navs

- docs/_includes/layouts/partials/header.njk
- docs/assets/javascript/cookies.js
- docs/assets/stylesheets/application.scss
- docs/assets/stylesheets/components/_cookie-banner.scss
This PR overrides the govuk cookie banner styles to left align the content to match the rest of the site.
It also makes a small adjustment to add the `hidden` attribute to the banner by default. This ensures the banner stays hidden and is only revealed by the JS if the user needs to accept or reject. This will prevent the "flash of cookie banner" sometimes visible on the site currently, where the banner displays, and is then hidden by the JS when it realises it's not needed.
Before:
After:
> docs(cookie banner): align cookie banner content left

- docs/_includes/example.njk
- docs/assets/stylesheets/components/_example.scss
- docs/assets/stylesheets/components/_tabs.scss
This PR makes a couple of minor tweaks to the coded examples:
* Adds top padding to the `<pre>` element, so that the 'copy code' button does not obscure long lines of code.
* Adds a white backgorund to the whole of the box around 'Open this example in a new tab'
* Updates the padding around the Figma tab content to match the other tabs.
**Before:**
**After:**
> docs(examples): add padding so that copy code button does not obscure the code

- docs/_includes/layouts/partials/get-help-and-contribute.njk
- docs/get-involved/suggest-a-change.md
- package-lock.json
- [Suggest a change page](https://design-patterns.service.justice.gov.uk/get-involved/suggest-a-change/) updated to more accurately reflect the process for users to suggest a change to a building block in the design system
> Updating suggest a change content

- docs/examples/multi-select/index.njk
- src/moj/all.js
- src/moj/components/multi-select/README.md
- src/moj/components/multi-select/multi-select.js
https://github.com/ministryofjustice/moj-frontend/issues/914
Add a optional 'idprefix' option to the multi-select component, so that the 'all' checkbox can have a unique id. Without this, multiple multi-selects on the same page don't work properly (selecting the second one 'all-selects' the first in Chrome, but YMMV)
None 
None - I have tried to ensure that the default id of the 'all' checkbox remains the same if the option is not provided.
This change is to support a feature in https://github.com/DFE-Digital/teaching-vacancies, where multiple tabs each have their own set of check-boxes. This change makes those check-boxes behave correctly and independently.
Fixed issue with multiple multi-selects appearing on the same page using new optional data-multi-select-idprefix.
> fix: (multi-select)  allow multiple multi-selects on same page

- docs/examples/pagination/index.njk
- src/moj/components/pagination/template.njk
* Changes pagination example results string starting point from 10 to 11.
* Fixes aria-label attribute end number to be total number of pages instead of total results.
> Changing pagination results number

- docs/_includes/layouts/partials/get-help-and-contribute.njk
An earlier pull request removed the contributor content from the documentation site. This PR removes the inclusion from the partial as it's no longer needed.
> Removing contributor partial

- .github/workflows/branch-preview.yml
- Dockerfile
- docker/htpasswd-preview
- docker/nginx-preview.conf
- kubernetes-deploy-preview.tpl
This PR adds a workflow to deploy a PR to a preview site when the label `preview:request` is added to the pull request.
Once successfully deployed, the label will be changed to `preview:active`.
Any subsequent pushes to the PR while the label remains applied will be automatically deployed out to the preview site.
On first deploy there may be a few minute delay before the site is available due to DNS rollout within the cluster.
The preview site is protected with httpauth like the staging site - username "preview" and password "moj" for all preview sites.
> build(preveiw): add a workflow to push a pr to branch preview

- .github/workflows/branch-preview-cleanup.yml
This PR creates a github action that runs when a PR is closed (or merged).  If the pull request has the label `preview:active` then this action will run.
It removes the kubernetes infrastructure for the preview site by issuing `kubectl delete` commands for the deployment, service and ingress that are created by the preview deploy action.
As a final step, it removes the `preview:active` label from the PR.
> build(preview): add branch preview cleanup workflow

- .releaserc.json
- gulp/build-javascript.js
- package-lock.json
- package.json
- src/moj/version.js
This PR should include the semantic release version number within the exported bundle js.
It does this by including a version.js file which contains a placeholder version string assigned to `MOJFrontend.version` 
There is then a plugin for semantic release which should be able to find and replace this string within the compiled js output 🤞
> feat(version): add version variable to bundle js

- .releaserc.json
- gulp/build-javascript.js
- gulp/build-styles.js
- gulpfile.js
- package-lock.json
- package.json
- src/moj/version.js
This PR adjusts the build:package task to also output a compiled minified js and css file. It also fixes the compiled output including jQuery, which didn't  work due to jQuery ending up bundled by the umd.
It also adds in a version string onto the MOJFrontend object, that should get updated by semantic release
> fix: include compiled css and js in the package

- src/moj/all.js
Removes the duplication of the code block to initialize sortable table components.
> fix(inital): remove duplicate initialisation block in all.js

- docs/_includes/layouts/base.njk
- docs/assets/stylesheets/govuk-frontend.scss
- docs/assets/stylesheets/moj-frontend.scss
- gulp/docs.js
The code in our examples was using `application.css` which is a sass compiled file including all of govuk frontend, moj-frontend and all the custom styles for the docs site.  This could cause potential issues where our own css could affect components. 
This PR refactors things such that the example layout includes compiled govuk-frontend and (separately) compiled moj-frontend and none of the docs site css. 
This ensure we are presenting (and testing) components in a more isolated way with no danger of style leakage.
> docs(examples): update example css to reflect real-life usage

- .github/workflows/deploy-production.yml
- .github/workflows/publish-package.yml
This PR updates the deploy and publish github actions to update the commit status based on the pass/fail status of the tests.
This should then allow us to update the branch rules to prevent merging if the tests are failing.
> ci: update the commit status with result of tests

- src/moj/components/date-picker/date-picker.spec.js
The cause of the flaky test seems to be the `getDateRangeInCurrentMonth` function within the tests. This was implemented before the addition of the `dayjs` library.
Now we have the date library to easily generate dates, we can remove the custom function and just manually add dayjs dates to an array.
> test(datepicker): remove test for length of excluded dates

- docs/assets/stylesheets/application.scss
- package-lock.json
This PR updates the docs site to use govuk-frontend 5.8.0
The only change required is to import `index.scss` instead of `all.scss` 
This is listed as a docs only change, as while the published bundle does draw in from the installed version of govuk frontend, it only requires `base.scss` and as such there will be no changes to the package, so we do not need to publish a new version.
> docs: update govuk-frontend to 5.8.0

- src/moj/components/date-picker/date-picker.js
Fixes all linting errors for the datepicker component.
Refactors the `setExludedDates` method to both fix linting errors and increase readability.
> Fix lint errors in datepicker and refactor setExcludedDates method

- docs/style-guide-updates.md
- removing category, and therefore caption from content style guide updates page.
> docs: removing category from style guide updates page

- docs/assets/stylesheets/application.scss
- docs/assets/stylesheets/govuk-frontend.scss
- gulp/build-styles.js
- gulp/dist.js
- gulp/docs.js
- package-lock.json
- package.json
Adding `quietDeps` removes a lot of noise when building the sass files. In order to use this, the `gulp-sass` dependency needed to be updated to the latest version which uses the new dart-sass js api.
> style(sass): upgrade gulp-sass to use new sass js api and use quietDeps

- docs/components/alert.md
- docs/components/button-menu.md
- docs/components/date-picker.md
- docs/components/interruption-card.md
Sub nav component (tabs) removed from alert, button menu, date picker, and interruption card component.
> Removing sub nav tabs from documentation pages

- .github/workflows/deploy-production.yml
- .github/workflows/publish-package.yml
Simple initial PR to set publishing a new version of the package to a manual trigger
> ci: switch publish action to workflow_dispatch trigger

- docs/_includes/layouts/home.njk
- Rogue space at the end of text on the documentation site home page.
- FIX: Space removed.
> Fixing typo on home page masthead.

- src/moj/components/alert/_alert.scss
- src/moj/components/alert/template.njk
Tweaks to the line-height and margins for headings on the alert component.  Instead of a fixed line-height(!?) the headings now use the default line height for govuk headings.  This also required small tweaks to the padding and margins for the headings too.
**Before:**
**After:**
> fix(alert): fix line-height on smaller screens

- docs/_includes/layouts/index.njk
- docs/assets/stylesheets/application.scss
- docs/assets/stylesheets/components/_app-article.scss
#1238 Missing articles on index pages
Applied an article to render like previous implementation
N/a
N/a
Run a visual check to ensure pages render as before
N/a
> fix: 1238 missing articles on index pages

- docs/components/alert.md
Removed extra word 'want' from sentence.
> docs: correct typo

- src/moj/components/button-menu/template.njk
The `itemClassNames` variable was declared outside the items loop and only ever appended to without being reset. 
This PR updates the template to declare a `defaultItemClassNames` variable outside the loop and then set an internally scoped `currentItemClassNames` variable within the loop to ensure item classes don't leak.
fix #969
> fix(button menu): item classes now only applied to the correct item

- src/moj/components/button-menu/_button-menu.scss
- src/moj/components/button-menu/button-menu.mjs
This PR adds a class to the single button version of the button menu to fix alignment issues when grouped in the identity bar component.
fix #1285
> fix(button menu): add a class to the single button version of the button menu

- docs/components/sortable-table.md
- docs/examples/sortable-table/index.njk
- src/moj/components/sortable-table/_sortable-table.scss
- src/moj/components/sortable-table/sortable-table.mjs
- src/moj/components/sortable-table/sortable-table.spec.mjs
Fixes an issue where screenreaders would announce the utf-8 icon characters within the pseudo elements.  
This PR swaps the pseudo elements for inline svg elements so that screenreader users get a better experience.
> fix(sortable table): use svg arrows instead of pseudo elements

- docs/_includes/layouts/home.njk
- docs/_includes/macros/card/template.njk
- docs/stylesheets/components/_app-card.scss
This PR refactors the card macro to be simpler, and not contain any of the govuk grid classes itself.
This makes the card width agnostic - it is always full width within the container it is placed within.
This makes the component macro itself much simpler, and makes it much more flexible to use.
**Before:**
**After:**
> refactor(card macro): update card macro to not include grid classes

- docs/_data/env.js
- docs/_includes/layouts/home.njk
- docs/_includes/macros/card/template.njk
- docs/stylesheets/application.scss
- docs/stylesheets/components/_app-card.scss
- docs/stylesheets/components/_app-grid.scss
- views/common/homepage-nav.html
This PR replaces the govuk grid classes on the homepage for a flexible auto layout grid based on css grid.
This allows for very flexible layouts, and eliminates the need for media queries.
The grid component can be customised using css variables, which can be set using inline styles on the component itself, or it can fall back to defaults.
> Use a flexible auto-grid for homepage layout

- package/package.json
Loosens the peer dependency version for govuk-frontend to `^5.8` 
5.8 is the minimum version due to needing the govuk base component class
This allows users to upgrade minor versions of govuk-frontend
> fix(dependencies): set govuk-frontend peer depencency version

- schema/add-assistive-tech.schema.js
- schema/add-external-audit.schema.js
- schema/add-internal-audit.schema.js
- views/community/pages/add-assistive-tech.njk
- views/community/pages/add-external-audit.njk
- views/community/pages/add-internal-audit.njk
This PR removes the accessibility report uploads and makes the issues discovered fields for the accessiblity sections required.
This is due to accessibility reports not being publishable to the public domain, but we still need to know the findings from the audits done.
> Remove accessibility report uploads

- config.js
- helpers/next-page.js
- schema/add-assistive-tech.schema.js
- schema/add-external-audit.schema.js
- schema/add-internal-audit.schema.js
In preparation for potential future config changes this PR moves the conditions for the next page into its own `conditions` key on the `COMPONENT_FORM_PAGES` object
> docs(wip): move conditions config to a key in config

- config.js
- views/community/pages/component-image.njk
For v1 of the contributions we have decided that we don't need to accept more than one image. This reduces our workload and enables us to ship sooner.
This PR removes the ui to add another image.
> Remove multiple image uploads

- config.js
- helpers/check-your-answers.js
- helpers/mockSessionData/sessionData.js
- helpers/text-helper.js
- middleware/process-subission-data.js
- routes/add-component.js
- views/community/pages/your-details.njk
Updates for the share details presentation on the CYA page
* Update the key for `TeamName` option
* Ensure `shareYourDetails` gets submitted even when no item is checked
* Update the labels that are displayed on the CYA page.
> Personal detail sharing fixes

- middleware/process-subission-data.js
This PR updates the contribution submission to create individual files for each of the code examples provided (unless the language chosen is 'other')
This means that when the PR is created Github code scanning will run on the code files.
> docs(contribution): save code examples as individual files 

- docs/prototyping/setting-up-coded-prototypes.md
`--` was erroneously deleted which meant `setting-up-coded-prototypes.md` wasn't rendering with styling or appearing in the sidebar.
> docs: fix missing page

- docs/stylesheets/components/_footer.scss
Adding `max-width` to footer to ensure width of footer matches width of content and sidebar.
Before:
After:
> docs: fix footer width

- src/moj/components/sortable-table/sortable-table.mjs
fix #1506 
Typo: correct `vviewBox` to `viewBox`
> fix(sortable-table): fix typos in viewbox attributes

- src/moj/components/date-picker/date-picker.mjs
- src/moj/components/date-picker/date-picker.spec.mjs
fix #1591
Fixes an issue where presing <kbd>Enter</kbd> anywhere in a form containing a datepicker would not submit the form as it should.
Some of the buttons within the datepicker did not have `type="button"` so were being activated by the <kbd>Enter</kbd> press as they were the first "submit" button in the form.
> fix(date picker): fix enter key not submitting parent form

- config.js
- docs/javascripts/copy.mjs
- docs/stylesheets/components/_example.scss
- docs/stylesheets/components/_tabs.scss
- middleware/generate-documentation.js
- views/community/pages/component-code-details.njk
> QA fixes II

- docs/_includes/layouts/base.njk
Adds a CSP nonce to the application.js file. This was triggering CSP error in Sentry
> docs: add csp nonce to main application js module

- docs/components/calendar.md
- docs/components/inset-text-highlighted.md
- docs/components/interruption-card.md
- docs/components/progress-tracker.md
Adds curly quotes around the component name in the new experimental components.
"fixes" a weird bug with li's containing p tags if they are the last thing in a tab shortcode. This is a bit of a hack, but it works!
> docs: minor text tweaks - adding curlies around component names

- app/app.js
Fully enables the CSP. No issues have been reported to sentry in two weeks, so it should be fine to enforce the rules
> docs: turn off report-only mode for content security policy

- .github/workflows/publish-package.yml
the permissions block seems to be supercede or override the admin pat token
> ci: remove permissions for publish semantic release step
